language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t simpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true simpleweb npm run start

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "simpleweb"
  env: "Simpleweb-env"
  bucket_name: "elasticbeanstalk-eu-west-3-310436991991"
  bucket_path: "simpleweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

