sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t simpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true simpleweb npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'simpleweb2'
  env: 'Simpleweb2-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-310436991991'
  bucket_path: 'simpleweb2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
